name:Super-Linter

on:push

jobs:
  super-linter:
    name: Lint code base
    runs-on: ubantu-latest
    steps:
      - name: Checkout code
        users:actions/Checkuot@v2

      - name: Run Super-Linter
        users:github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
